name: rl-lab-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pygame
  - ruff
  - pre-commit
  - numpy
  - gymnasium
  - ipykernel
  - tqdm
  - ipywidgets
  - matplotlib
  - pandas
  - ipympl
