name: Ruff
on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
